### ISSUE TITLE
step10 R problem

### ISSUE THREAD

**Issue by Niohuruzh** [amsession/Kmer-based-Subgenome-Mapping#1]
Hi, dear
When I run step10, there is a problem that 
```
Error in my.dat : object 'my.dat' not found
Execution halted
```
I don't know what that's mean. Could you help me ?
Thanks for your scripts.
I'm looking forward to hearing back from you.
Best wishes!

**Comment by YongZhou2019** [comment]
Hello, I am facing the same issue, could you please let me know how to fix it?

"""
 cat my.error.log1 
Error in my.dat : object 'my.dat' not found
Execution halted
"""


Thanks very much,
Yong

**Comment by amsession** [comment]
Fixed this with latest version of scripts.
