### ISSUE TITLE
Rscript run time

### ISSUE THREAD

**Issue by HorticLee** [amsession/Kmer-based-Subgenome-Mapping#3]
Hello,  I ran the Rscript  to run the initial k-mer search analysis 2 days ago, but there is still no result today. 
How much time it usually takes?

**Rscript Kmap.2subgenome.identification.R filt.k13.tbl homeolog.pairs chr.lengths norm.tbl diff.kmer diff.kmer.tbl >&my.error.log1**
my.error.log.1 shows as fllows:
nohup: ignoring input

![Uploading github.png…]()

**Comment by amsession** [comment]
Fixed this with latest version of scripts.
