### ISSUE TITLE
Error in the R script line 19

### ISSUE THREAD

**Issue by shreena-pradhan** [amsession/Kmer-based-Subgenome-Mapping#4]
Thank you for developing this pipeline. I noticed in the R scripts Kmap.2subgenome.indentification.R (for all 3 that you provide), the object my.dat has not been previously defined and comes for the first time in line 19. If I could know what my.dat object needs to look like, I could complete this pipeline. Thanks!

**Comment by amsession** [comment]
Fixed this with latest version of scripts.
